SET SAFE OFF
? sqlexec(nconec,"select * from acceper;",'a')
select * from a into table acceperr
USE
? sqlexec(nconec,"select * from accesos;",'a')
select * from a into table accesosr
USE
? sqlexec(nconec,"select * from acti_inven;",'a')
select * from a into table acti_invenr
USE
? sqlexec(nconec,"select * from activosf;",'a')
select * from a into table activosfr
USE
? sqlexec(nconec,"select * from asientosdia;",'a')
select * from a into table asientosdiar
USE
? sqlexec(nconec,"select * from asientosmov;",'a')
select * from a into table asientosmovr
USE
? sqlexec(nconec,"select * from auditoria;",'a')
select * from a into table auditoriar
USE
? sqlexec(nconec,"select * from cobros;",'a')
select * from a into table cobrosr
USE
? sqlexec(nconec,"select * from ctasban;",'a')
select * from a into table ctasbanr
USE
? sqlexec(nconec,"select * from detadocb;",'a')
select * from a into table detadocbr
USE
? sqlexec(nconec,"select * from detadocd;",'a')
select * from a into table detadocdr
USE
? sqlexec(nconec,"select * from detadoci;",'a')
select * from a into table detadocir
USE
? sqlexec(nconec,"select * from detadoco;",'a')
select * from a into table detadocor
USE
? sqlexec(nconec,"select * from detadocs;",'a')
select * from a into table detadocsr
USE
? sqlexec(nconec,"select * from detadocu;",'a')
select * from a into table detadocur
USE
? sqlexec(nconec,"select * from detagruem;",'a')
select * from a into table detagruem
USE
? sqlexec(nconec,"select * from dgdoc;",'a')
select * from a into table dgdocr
USE
? sqlexec(nconec,"select * from docmul;",'a')
select * from a into table docmulr
USE
? sqlexec(nconec,"select * from docmuld;",'a')
select * from a into table docmuldr
USE
? sqlexec(nconec,"select * from documents;",'a')
select * from a into table documentsr
USE
? sqlexec(nconec,"select * from embarques;",'a')
select * from a into table embarquesr
USE
? sqlexec(nconec,"select * from gdoc;",'a')
select * from a into table gdocr
USE
? sqlexec(nconec,"select * from detagru;",'a')
select * from a into table detagrur
USE
? sqlexec(nconec,"select * from grudat;",'a')
select * from a into table grudatr
USE
? sqlexec(nconec,"select * from docuse;",'a')
select * from a into table docuser
USE
? sqlexec(nconec,"select * from ddocuse;",'a')
select * from a into table ddocuser
USE
? sqlexec(nconec,"select * from empleados;",'a')
select * from a into table empleadosr
USE
? sqlexec(nconec,"select * from empresas;",'a')
select * from a into table empresasr
USE
? sqlexec(nconec,"select * from haciendas;",'a')
select * from a into table haciendasr
USE
? sqlexec(nconec,"select * from items;",'a')
select * from a into table itemsr
USE
? sqlexec(nconec,"select * from monedas;",'a')
select * from a into table monedasr
USE
? sqlexec(nconec,"select * from periodos;",'a')
select * from a into table periodosr
USE
? sqlexec(nconec,"select * from plancuenta;",'a')
select * from a into table plancuentar
USE
? sqlexec(nconec,"select * from productores;",'a')
select * from a into table productoresr
USE
? sqlexec(nconec,"select * from programas;",'a')
select * from a into table programasr
USE
? sqlexec(nconec,"select * from rubros;",'a')
select * from a into table rubrosr
USE
? sqlexec(nconec,"select * from saldosb;",'a')
select * from a into table saldosbr
USE
? sqlexec(nconec,"select * from saldoscon;",'a')
select * from a into table saldosconr
USE
? sqlexec(nconec,"select * from secuban;",'a')
select * from a into table secubanr
USE
? sqlexec(nconec,"select * from secudoc;",'a')
select * from a into table secudocr
USE
? sqlexec(nconec,"select * from secuencias;",'a')
select * from a into table secuenciasr
USE
? sqlexec(nconec,"select * from secuwork;",'a')
select * from a into table secuworkr
USE
? sqlexec(nconec,"select * from sujetos;",'a')
select * from a into table sujetosr
USE
? sqlexec(nconec,"select * from variablesdiarias;",'a')
select * from a into table variablesdiariasr
USE
? sqlexec(nconec,"select * from workstations;",'a')
select * from a into table workstationsr
use
sele a
USE

